package code.utils;

public class AppUrls {

    //Live Url
   // public static final String baseUrl = "https://api.hathme.com/api/user/";

    //Dev
    public static final String baseUrl = "https://apidev.hathme.com/api/user/";
    public static final String register = baseUrl + "Register";
    public static final String login = baseUrl + "Login";
    public static final String otpVerification = baseUrl + "OtpVerification";
    public static final String generatePin = baseUrl + "GeneratePin";
    public static final String forgotPassword = baseUrl + "ForgotPassword";
    public static final String logout = baseUrl + "Logout";
    public static final String category = baseUrl + "Category";
    public static final String updateProfile = baseUrl + "UpdateProfile";
    public static final String userVerify = baseUrl + "UserVerify";
    public static final String myProfile = baseUrl + "MyProfile";
    public static final String searchCategory = baseUrl + "SearchCategory?search=";
    public static final String verifyPin = baseUrl + "VerifyPin";
    public static final String resendOtp = baseUrl + "ResendOtp";
    public static final String search = baseUrl + "Search";
    public static final String sendFriendRequest = baseUrl + "SendFriendRequest";
    public static final String pendingRequestList = baseUrl + "PendingRequestList";
    public static final String acceptFriendRequest = baseUrl + "AcceptFriendRequest";
    public static final String rejectRequest = baseUrl + "RejectRequest";
    public static final String myFriends = baseUrl + "MyFriends";
    public static final String createGroup = baseUrl + "createGroup";
    public static final String merchantListByCategory = baseUrl + "MerchantListByCategoryId";
    public static final String productListByMerchantId = baseUrl + "ProductListByMerchantId";
    public static final String productDetailedById = baseUrl + "ProductDetailedById";
    public static final String addToCart = baseUrl + "AddToCart";
    public static final String getProductFromCart = baseUrl + "GetProductFromCart";
    public static final String address = baseUrl + "Address";
    public static final String GetAddress = baseUrl + "GetAddress";
    public static final String deleteAddress = baseUrl + "DeleteAddress";
    public static final String updateAddress = baseUrl + "UpdateAddress";
    public static final String getCoupon = baseUrl + "GetCoupon";
    public static final String getBucketCoupon = baseUrl + "getBucketCoupon";
    public static final String applyCoupon = baseUrl + "ApplyCoupon";
    public static final String ApplyBucketCoupon = baseUrl + "ApplyBucketCoupon";
    public static final String removeCoupon = baseUrl + "RemoveCoupon";
    public static final String RemoveBucketCoupon = baseUrl + "RemoveBucketCoupon";
    public static final String placeOrder = baseUrl + "PlaceOrder";
    public static final String orderList = baseUrl + "OrderList";
    public static final String orderDetail = baseUrl + "OrderDetail";
    public static final String RemoveProductsFromCart = baseUrl + "RemoveProductsFromCart";
    public static final String repeatOrder = baseUrl + "repeatOrder";
    public static final String getNearbyMerchants = baseUrl + "getNearbyMerchants";
    public static final String getCountryList = baseUrl + "getCountryList";
    public static final String CancelOrder = baseUrl + "CancelOrder";
    public static final String personalDetail = baseUrl + "personalDetail";
    public static final String transactionHistory = baseUrl + "TransactionHistory";
    public static final String addBank = baseUrl + "AddBank";
    public static final String BankList = baseUrl + "BankList";
    public static final String UpdateBank = baseUrl + "UpdateBank";
    public static final String DeleteBank = baseUrl + "DeleteBank";
    public static final String withdrawal = baseUrl + "withdrawal";
    public static final String depositAmount = baseUrl + "DepositAmount";
    public static final String settings = baseUrl + "getProjectSetting";
    public static final String rateUser = baseUrl + "rateUser";
    public static final String sellGreenPoints = baseUrl + "sellGreenPoints";
    public static final String setFavorite = baseUrl + "setFavorite";
    public static final String favoriteProductList = baseUrl + "favoriteProductList";
    public static final String deleteFavorite = baseUrl + "deleteFavorite";
    public static final String setMerchantFavorite = baseUrl + "setMerchantFavorite";
    public static final String favoriteMerchantList = baseUrl + "favoriteMerchantList";
    public static final String DeleteFavoriteMerchant = baseUrl + "DeleteFavoriteMerchant";
    public static final String acceptPoints = baseUrl + "acceptPoints";
    public static final String cardScratch = baseUrl + "cardScratch";
    public static final String getAllScratchCard = baseUrl + "getAllScratchCard";
    public static final String orderReview = baseUrl + "orderReview";
    public static final String driverOrderRating = baseUrl + "driverOrderRating";

    public static final String CreateWithdrawalPin = baseUrl + "CreateWithdrawalPin";
    public static final String VerifyWithdrawalPin = baseUrl + "VerifyWithdrawalPin";
    public static final String walletToWalletTransfer = baseUrl + "walletToWalletTransfer";
    public static final String ResetWithdrawalPin = baseUrl + "ResetWithdrawalPin";
    public static final String GetMssageList = baseUrl + "GetMssageList";
    public static final String createMerchantChannel = baseUrl + "createMerchantChannel";
    public static final String createVideoChannel = baseUrl + "createVideoChannel";
    public static final String videoChatList = baseUrl + "videoChatList";
    public static final String stopVideoChat = baseUrl + "stopVideoChat";
    public static final String startCall = baseUrl + "startCall";
    public static final String endCall = baseUrl + "endCall";
    public static final String callHistory = baseUrl + "callHistory";
    public static final String uploadImage = baseUrl + "uploadImage";
    public static final String searchAllproductList = baseUrl + "searchAllproductList";
    public static final String getVideoList = baseUrl + "getVideoList";
    public static final String listAllVideos = baseUrl + "listAllVideos";
    public static final String uploadVideo = baseUrl + "uploadVideo";
    public static final String addUserInCall = baseUrl + "addUserInCall";
    public static final String getGroupMembers = baseUrl + "getGroupMembers";
    public static final String deleteGroup = baseUrl + "deleteGroup";
    public static final String leaveGroup = baseUrl + "leaveGroup";
    public static final String updateGroupName = baseUrl + "updateGroupName";
    public static final String getInviteMemberList = baseUrl + "getInviteMemberList";
    public static final String addNewGroupMember = baseUrl + "addNewGroupMember";
    public static final String createGroupVoiceCall = baseUrl + "createGroupVoiceCall";
    public static final String getGroupVoiceCallList = baseUrl + "getGroupVoiceCallList";
    public static final String shareVideo = baseUrl + "shareVideo";
    public static final String overview = "https://apidev.hathme.com/Overview";
    public static final String policyUrl = "https://apidev.hathme.com/Policy";
    public static final String videoDetail = baseUrl + "videoDetail";
    public static final String SendNotification = baseUrl + "SendNotification";
    public static final String updateNotificationStatus = baseUrl + "updateNotificationStatus";
    public static final String getNotificationStatus = baseUrl + "getNotificationStatus";
    public static final String userRequestMerchantOrder = baseUrl + "userRequestMerchantOrder";
    public static final String RequestUserOrderList = baseUrl + "RequestUserOrderList";
    public static final String bucketProductList = baseUrl + "bucketProductList";
    public static final String removeOrderItem = baseUrl + "removeOrderItem";
    public static final String bucketOrderPlace  = baseUrl + "bucketOrderPlace";
    public static final String likeVideo  = baseUrl + "likeVideo";
    public static final String dislikeVideo  = baseUrl + "dislikeVideo";
    public static final String viewVideo  = baseUrl + "viewVideo";
    public static final String commentVideo  = baseUrl + "commentVideo";
    public static final String listAllVideoComment  = baseUrl + "listAllVideoComment";
    public static final String reportVideo  = baseUrl + "reportVideo";
    public static final String notIntersted  = baseUrl + "notIntersted";
    public static final String WatchLater  = baseUrl + "WatchLater";
    public static final String HideWatchLaterVideos  = baseUrl + "HideWatchLaterVideos";
    public static final String defaultAddress  = baseUrl + "defaultAddress";
    public static final String getwatchLaterVideos  = baseUrl + "getwatchLaterVideos";
    public static final String subscribeChannel  = baseUrl + "subscribeChannel";
    public static final String unSubscribeChannel  = baseUrl + "unSubscribeChannel";
    public static final String showWatchHistory  = baseUrl + "showWatchHistory";
    public static final String mySubscriptionList  = baseUrl + "mySubscriptionList";
    public static final String channelVideos  = baseUrl + "channelVideos";
    public static final String messageCount  = baseUrl + "messageCount";

    public static final String privacyPolicy = "http://hathme.com/privacy.html";

    public static final String About = "https://apidev.hathme.com/About";
    public static final String faq = "https://apidev.hathme.com/faq";
    public static final String tnc = "http://hathme.com/term.html";
    public static final String shareUrl = "https://hathme.com/merchant.html?merchantId=";
}